name: deploy

on:
    workflow_run:
        workflows: [test] # Triggered by the test workflow
        types: [completed] # The test workflow must complete
        branches: [Public-Cloud-Infrastructure]

jobs:
    on-success:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }} # Only when test completed successfully 
        steps:
            - uses: actions/checkout@v2
            
            - name: Install backend dependencies
              working-directory: backend
              run: npm install
      
            - name: Install frontend dependencies
              working-directory: frontend
              run: npm install
      
            - name: Build frontend
              working-directory: frontend
              run: npm run build
              
            - name: Package application
              run: cd frontend && zip -r videogamecatalog-${{ github.run_id }}.zip ./dist  

            - name: Upload application artifact
              uses: actions/upload-artifact@v3
              with:
                name: vgc-artifact
                path: frontend/videogamecatalog${{ github.run_id }}.zip

            - name: Congifure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
                aws-region: "us-east-1" 

            - name: Upload application file to AWS
              run: aws s3 cp frontend/videogamecatalog${{ github.run_id }}.zip s3://terraform-state-videogamecatalog-kevinzheng0701${{ github.run_id }}.zip

            - name: Create new application version
              run: |  
                aws elasticbeanstalk create-application-version \
                --application-name mernstack \
                --source-bundle S3Bucket="terraform-state-videogamecatalog-kevinzheng0701",S3Key="videogamecatalog${{github.run_id}}.zip " \

            - name: Deploy application
              run: aws elasticbeanstalk update-environment --environment-name mernstack-environment --version-label videogamecatalog${{ github.run_id }}
